Authentication
divinecharlotte/blog-app pull request #11
Opened 2022-09-28 13:42 UTC by divinecharlotte

2022-09-28 15:00 UTC, alexander16108 requested changes
Hi TEAM 👋🏾 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
There is only a minor problem when running your app on the web fix this and you will be good to go

<img src="https://media2.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif" style="height50px"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 15:00 UTC, alexander16108 commented on config/initializers/devise.rb
> +  # enable it only for database (email + password) authentication.
currently your application is throwing this error when running the app

![image](https://user-images.githubusercontent.com/60612329/192813525-f198b017-489d-42a5-a479-a6275c9295a5.png)

2022-09-28 15:43 UTC, divinecharlotte commented on config/initializers/devise.rb
> +  # enable it only for database (email + password) authentication.
Hey @alexander16108 my app is working correctly on my side and I can't get how to fix the error you are getting once I don't have it on my side you may check again well or we join a call and I show you my app running

2022-09-28 16:00 UTC, nottherealalanturing commented on config/initializers/devise.rb
> +  # enable it only for database (email + password) authentication.
The problem is with your database credentials @alexander16108

2022-09-28 17:57 UTC, merged

2022-09-29 12:22 UTC, alexander16108 commented on config/initializers/devise.rb
> +  # enable it only for database (email + password) authentication.
I just realised that now after I made changes on the database credentials @divinecharlotte 

thank you for pointing that out I just learnt something new today 👍🏾 💯  👏🏾